### ISSUE TITLE
Set relative path

### ISSUE THREAD

**Issue by aronlindberg** [aronlindberg/hub_turkr#3]
In the `execute.R` script you need to set a relative path per https://github.com/aronlindberg/lab_notebook/blob/master/2015-09-20-scripting-templates.md#relative-paths

The path should go to the base git folder, where `hub_turkr` is a subfolder.

**Comment by aronlindberg** [comment]
This is still not working. The reason it's not working is that in `execute.R` R cannot find `working_directory.R` without a proper path. I think a solution might be to make sure that the `.Rproj` file works - this should open Rstudio in the base directory, and then you make all paths relative to that...i.e. you need to specify that the path is `/R/working_directory.R` etc.

**Comment by bilakhiaricky** [comment]
commit # b8a24f6
this program as the format of cresting the working_directory.
after creating working_directory it should be placed in R folder for the program to work.
