### ISSUE TITLE
Create a way to store credentials safely

### ISSUE THREAD

**Issue by aronlindberg** [aronlindberg/hub_turkr#5]
Guidance is here: https://github.com/aronlindberg/lab_notebook/blob/master/2015-09-20-scripting-templates.md#storing-credentials-in-a-safe-way

The standard credentials file from AWS is called `rootkey.csv.txt` and has the following format:

```
AWSAccessKeyId=ACCESSKEYID
AWSSecretKey=SECRETKEY
```

Just read that file, replace `=` with `<-` (do this programmatically using a UNIX command or through rewriting the file from R)

**Comment by bilakhiaricky** [comment]
commit # ab665e4.
for login, rootkey file having credential in it is to be stored in R folder.
this program fetches the value from it and assigns to credential function which helps to login to AWS.
