### ISSUE TITLE
Turn of auto-save

### ISSUE THREAD

**Issue by aronlindberg** [aronlindberg/hub_turkr#7]
Here: https://github.com/bilakhiaricky/hub_turkr/blob/master/hub_turkr.Rproj

You generally want to turn off saving history and workspace, because you don't want to rely on hidden variables or global variables for your code to run. The idea is that you should be able to start a fresh R session, and then run the code fresh.

**Comment by bilakhiaricky** [comment]
commit # 8712141.
Restore workspace, save workspace and history are set to None value from the default value.
