### ISSUE TITLE
Fix faulty .Rproj file

### ISSUE THREAD

**Issue by aronlindberg** [aronlindberg/hub_turkr#8]
There is a problem with the.Rproj file:
![untitled](https://cloud.githubusercontent.com/assets/1494523/11128986/0e36f532-894b-11e5-802b-0b4aa902af47.png)

Can you a) explain why this is happening, and b) fix it and explain how it was fixed?

**Comment by bilakhiaricky** [comment]
Can you please upload the image again as it is not visible.
